### ISSUE TITLE
Problems installing pdfbooklet on Devuan Jessie 64

### ISSUE THREAD

**Issue by nazmifr** [Averell7/PdfBooklet#10]
Hi,

I tried installing today, I did as follows:

1) git clone the main branch
2) sudo apt-get install python-gtk2 python-poppler
3) sudo python setup.py install

Everything seemed to go fine

4) pdfbooklet

First error, it didn't want to start because apparently poppler wasn't available:

`ValueError: Namespace Poppler not available`

I searched on google and found this: [link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832479)
so I installed gir1.2-poppler-0.18

Now I have:

```
2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
Error: Could not import pdfbooklet
Cause: No module named PyPDF2_G

```

Do you have an idea of what might be wrong?

I found this guy [link](https://stackoverflow.com/questions/12780668/cannot-install-pypdf-2-module )
the problem seems similar though I'm no dev, I don't know what to fix

Thanks in advance for any help and thanks for your program that seems to be awesome.

**Comment by Averell7** [comment]
Hello, 
sorry for the late answer, Linux support is poor, unfortunately because I had not a Linux box. I just installed a Rasperry PI 3B+ and it is now much easier to check. 
Probably the best solution to install on debian would be to use the .deb file of the 3.0.4 version, on https://sourceforge.net/projects/pdfbooklet/files
In my install on the Raspberry (which has a small debian), python files are installed in :

    /usr/local/lib/python2.7/dist-packages/pdfbooklet 
And **there must be** a subdirectory PyPDF2_G with the corresponding library inside. 
I am not sure if the setup you have done has copied it correctly. It is a modified version of the PyPDF2 module which was too slow for merging pages. I will test that and modify setup.py if necessary. 

Note that normally pdfbooklet 3.x.x runs in python 3, but it is compatible with 2.7. 
Here are all the dependencies (for python 2.7 and python 3). 

    python3-cairo, python-gobject-cairo, python-gi-cairo, python3-gi, gir1.2-gtk-3.0, gir1.2-poppler-0.18

**Comment by Averell7** [comment]
It would be great if you could help me to write a text for Linux users about the known problems in Linux, and how to overcome them. And also help me test the new versions. 
You can write me directly on : dy1977@orange.fr, it will be easier. Thanks
